### ISSUE TITLE
New blinds

### ISSUE THREAD

**Issue by tiimbo82** [XattSPT/homey-SomaSmartShades#1]
Hi, so excited to see this on Homey, thanks for bringing across.
Unfortunately it doesn't see my blinds, I think it may be the same issue I assisted with here in that newer blinds identify differently: https://github.com/andersonshatch/soma-ctrl/issues/27

**Comment by XattSPT** [comment]
@tiimbo82 I'll took a look on it and try to publish a new updated version to solve this. I'll be publshing here as a branch for your test before official release.

**Comment by XattSPT** [comment]
@tiimbo82 I've sent a new version as a beta, I supose it will be available soon on Homey App, if you can try it and tell me any problems, it will help me a lot. I do not have any new device and I cant try if it works correctly.

**Comment by tiimbo82** [comment]
You're amazing, it found them, thank you!
