### ISSUE TITLE
Support for Soma Shades 2

### ISSUE THREAD

**Issue by esaborg** [XattSPT/homey-SomaSmartShades#12]
Any change of getting support for Soma Shades 2?

**Comment by XattSPT** [comment]
@esaborg as far as I know, Soma Shades 2 do not have any difference on control, have you tried to add to Homey? It should works.  
If doesn't work, could you tell me why you can add it? you don't find them on adding device screen?

**Comment by esaborg** [comment]
I have tried to add the Soma Shades 2 to my Homey, but adding the device times out. ("Timed out after 30000ms.") Due the timeout I can't find the device from the add device screen and here we are. I have installed the official Soma Smart Shades app as the Homey app suggests and with it the shade works as expected. 

As a troubleshoot I have turned off Bluetooth from my phone to make sure that the device is not connected any other device, but that have not changed the situation and Homey still can't find the device.

I'm running Homey version 5.0.4

**Comment by XattSPT** [comment]
Can u share the name of the device?

In v1 are RISExxx or something like this?

El dv, 26 març 2021 a les 14:32 esaborg ***@***.***> va
escriure:

**Comment by esaborg** [comment]
Here's details bluetooth scanner provided:
Title | Value
-----|-------
Device major class code | 7936
Device class code | 7936
Manufacturer name | WazombiLabs
Software revision | v2.2.7
Hardware revision | BLINDY_V9
Name | S

Name of the device seems to be just capital letter `S`

**Comment by XattSPT** [comment]
As I expected… it should work….

I will take a look to check if everything is ok.

You can Try to close soma app on mobile (or other device U use to control
shades) then reboot homey and after reboot try again. Some time homey
bluetooth crashes.

El dv, 26 març 2021 a les 15:14 esaborg ***@***.***> va
escriure:

**Comment by aCrazyAfro** [comment]
I was wondering if the SOMA Smart Shades 2 already is working on this app without the control unit from SOMA.

**Comment by XattSPT** [comment]
My soma 2 is working without problems. Have u got any problems?

**Comment by aCrazyAfro** [comment]
No problems, was wondering is this 2 was working on this Homey app. Am looking into purchasing the Soma 2 and whether it works with Homey. Thanks for your reply!
