### ISSUE TITLE
App unresponsive on Homey

### ISSUE THREAD

**Issue by dajoneseng** [XattSPT/homey-SomaSmartShades#13]
Hi Gerard,

I’ve been using your app in a flow with hue dimmer to open/close my soma blinds but it’s recently stopped working. Can you advise how I can troubleshoot/pinpoint the issue. The hue pet of the flow works, the soma app seems unresponsive. 

Diagnostics log is 2eeaef1c-8ff9-4e20-a6b4-2571e3d6cf7d

Many thanks,

Dale

**Comment by XattSPT** [comment]
Bluetooh on homey sometimes stop responding. Best way is to reboot homey. I have a flow to reboot homey every nigth, since then I have not got any problems with bluetooth freezing.
