### ISSUE TITLE
SomA smartshades on homey hub

### ISSUE THREAD

**Issue by ronwell74** [XattSPT/homey-SomaSmartShades#8]
I have been using soma smart shades without any issue since I got homey 6 months ago. Just recently the shade stoped responding to my flows. they do eventualy work, if i repeat the flows several times.

**Comment by XattSPT** [comment]
dear @ronwell74, I'm also having some problems. It seems that Homey are changing some configuration on Bluetooth code on Homey and some times it does not work correctly. 

A couple of thing you can do: 
  - Reboot your homey. (some times solve this problem)
  - Be sure you are on version 4.2.0 on homey software, last experimental updates (...rc-11 or rc-12 the bluettoth were very problematic). Last version 4.2.0 seems to work most of time.

**Comment by ronwell74** [comment]
yes my homey is upto date with the latest version. restarting homey does
help sometimes, but not always. i have a schedule to restart homey at 2am
every night. and the first schedule for my blinds is at 7am. usually 2 out
4 blinds don't respond. is there an app for homey that will improve its
Bluetooth?

**Comment by XattSPT** [comment]
Dear @ronwell74, mine are working as well as we can expect using bluetooth (some times do not go).  

Bluetooth is hardware inside homey. Homey Team are improving it, but sometimes seems they go one step behind. Nothing else to do on this side... 

What you could try, if you open theese number of devices is try to delay a couple of seconds from eachother on flow, this could help to improve results (set to move one blind every 2 or 3 seconds adding delays at each device (0-2-4-6)).

**Comment by ronwell74** [comment]
yes I have set up 1 minute delays between each blind action, I have even set up a repeat, with a contion if blinds are not at % then start the previous flow. I have also noticed after they didn't move the devices are powered off, would adding a turn blind on card first help.
