### ISSUE TITLE
Soma update 2.0.6

### ISSUE THREAD

**Issue by kjettern** [XattSPT/homey-SomaSmartShades#9]
Hello.
After updating my blinds to v2.0.6 I can't get them to work with Homey. It was working before the update. I've tried adding the shades to homey from scratch and homey finds the Soma. No battery indication and no response from the shade. Can you look into it?

**Comment by XattSPT** [comment]
@kjettern did you updated homey software? Last versions of homey have problems with bluetooth devices! Hope they will solve soon.

You can try to reboot homey. Some times works (at least during some time).

**Comment by kjettern** [comment]
Yes updated to 5.0r22.. Soma was working, but after the Soma firmware update it wasn't. Hopefully it will start working again when Athom get their s**t together 😅

**Comment by XattSPT** [comment]
How did u get 2.0.6? Last public is 1.0.2...

El dg, 9 ag 2020 a les 12:00 kjettern <notifications@github.com> va
escriure:

**Comment by kjettern** [comment]
> How did u get 2.0.6? Last public is 1.0.2... El dg, 9 ag 2020 a les 12:00 kjettern <notifications@github.com> va escriure:
> […](#)

I just pressed troubleshooting in the app and pressed firmware update. I got fw 2.0.6 after that. Now my shades are moving faster up and down. 
![Screenshot_20200810-211849](https://user-images.githubusercontent.com/46543246/89821795-76305600-db4f-11ea-9a90-1eeb042c301b.jpg)

**Comment by XattSPT** [comment]
Oh I see that you updated Soma devices. I'll try to update one of mines and
try if my app works in new update of soma devices.... or if it needs any
change.

I'll come back to you after checking it.

El dl, 10 ag 2020 a les 21:21 kjettern <notifications@github.com> va
escriure:

**Comment by mcfetz** [comment]
Hi Gerard,
I got my two soma shades today. Both are on firmware 2.0.6 and both won't work together with homey. :-(

I cloned your repository and installed the app from command line to get logging. I often get timeouts while connecting the devices. After restarting homey sometimes a devices works or none of them...

─────────────── Logging stdout & stderr ───────────────                                                                                                                                        [45/785]
Successfully init Soma version: 1.0.2
updatedevice
updatedevice
value mqtt:  100
timeout, retry again 1 device: SomaSmarthade fc803a15d74c
updatedevice
timeout, retry again 2 device: SomaSmarthade fc803a15d74c
updatedevice
timeout, retry again 3 device: SomaSmarthade fc803a15d74c
Max retries exceeded, no success - Device: SomaSmarthade fc803a15d74c
Time:[object Object]
Time:[object Object]
Time:[object Object]
Time:[object Object]
updateposition
Time:45000
updateposition
Time:45000
updatedevice
value mqtt:  93
updatedevice
value Set:  0
updateposition
Time:45000
value Set:  0
updateposition
Time:45000
value Set:  0
updateposition
Time:45000
(node:2367) UnhandledPromiseRejectionWarning: Error: BLETimeout
   at Remote IPC Process

(node:2367) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which
was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_reject
ions_mode). (rejection id: 1)
(node:2367) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit c
ode.
(node:2367) UnhandledPromiseRejectionWarning: Error: BLETimeout
   at Remote IPC Process

(node:2367) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which
was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_reject
ions_mode). (rejection id: 2)
value Set:  1
updateposition
Time:45000
updatedevice
value Set:  0
updateposition
Time:45000
value Set:  1
updateposition
Time:45000
updatedevice
value Set:  0
updateposition
Time:45000
(node:2367) UnhandledPromiseRejectionWarning: Error: BLETimeout
   at Remote IPC Process

(node:2367) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which
was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_reject
ions_mode). (rejection id: 1)
(node:2367) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit c
ode.
(node:2367) UnhandledPromiseRejectionWarning: Error: BLETimeout
   at Remote IPC Process

(node:2367) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which
was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_reject
ions_mode). (rejection id: 2)
value Set:  1
updateposition
Time:45000
updatedevice
value Set:  0
updateposition
Time:45000
value Set:  1
updateposition
Time:45000
updatedevice
value Set:  0
...



any idea?
updatedevice
updatedevice
value Set:  0.6
updateposition
Time:45000
timeout, retry again 1 device: SomaSmarthade cbc17ba5f881
updatedevice
timeout, retry again 1 device: SomaSmarthade fc803a15d74c
updatedevice
(node:16549) UnhandledPromiseRejectionWarning: Error: BLETimeout
   at Remote IPC Process

(node:16549) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:16549) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
timeout, retry again 2 device: SomaSmarthade cbc17ba5f881
updatedevice
timeout, retry again 2 device: SomaSmarthade fc803a15d74c
updatedevice

**Comment by kjettern** [comment]
Update: Now my soma responds to Homey again! Seems like the current app is working with fw 2.0.6! I'm on the Homey beta and its a pain in the *ss and whenever theres an update they break something new.. At least Soma and BT works for now!
